### ISSUE TITLE
concurrent write to websocket

### ISSUE THREAD

**Issue by yookoala** [tomatorpg/tomatorpg#55]
## Steps to Reproduce

1. Enter any room.
2. Go back to room list.
3. Enter any room again (either the original room or another).
4. Type a message and send.

## Expected Result

Message send and the chat history displays the message.

## Actually Got

The server process halt. Server log of such event would look like this:

```
2018/01/17 10:50:41.897454 database migration done
2018/01/17 10:50:41.897655 production mode
2018/01/17 10:50:41.897731 listen to port 8080
2018/01/17 10:50:45.781365 request_id=elrlLEfwNEbGKhZUqCBb at=info method=GET path=/rooms/11 protocol= remote_addr=127.0.0.1:52424
2018/01/17 10:50:46.064040 request_id=LInrnCeXGSpCJXQdPOGb at=info method=GET path=/api.v1 protocol= remote_addr=127.0.0.1:52426
2018/01/17 10:50:46.064180 request_id=LInrnCeXGSpCJXQdPOGb at=info message="websocket connection upgrade success"
2018/01/17 10:50:46.232899 request_id=LInrnCeXGSpCJXQdPOGb at=info action=rooms.list len(room)=11
2018/01/17 10:50:46.233574 request_id=LInrnCeXGSpCJXQdPOGb at=info action=roomActivities.list room.id=11
2018/01/17 10:50:58.209660 request_id=LInrnCeXGSpCJXQdPOGb at=info action=roomActivities.list room.id=11
2018/01/17 10:51:13.927670 request_id=LInrnCeXGSpCJXQdPOGb at=info action=roomActivity.create user.id=0 room.id=11 activity.action=message activity.message="message that kills the server" activity.meta=
panic: concurrent write to websocket connection

goroutine 30 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc420207950, 0x1, 0x0, 0x0, 0x0, 0x60, 0x95f0c0)
	/home/foobar/.gopath/src/github.com/gorilla/websocket/conn.go:585 +0x75c
github.com/gorilla/websocket.(*messageWriter).Close(0xc420207950, 0x95f0c0, 0xc42016e780)
	/home/foobar/.gopath/src/github.com/gorilla/websocket/conn.go:699 +0x69
github.com/gorilla/websocket.(*Conn).prepWrite(0xc4200b0000, 0x1, 0xc420033e18, 0x43732e)
	/home/foobar/.gopath/src/github.com/gorilla/websocket/conn.go:468 +0x113
github.com/gorilla/websocket.(*Conn).NextWriter(0xc4200b0000, 0x1, 0x40fcf6, 0xc42016e780, 0x600000000978fd3, 0xffffffffffffffff)
	/home/foobar/.gopath/src/github.com/gorilla/websocket/conn.go:488 +0x39
github.com/gorilla/websocket.(*Conn).WriteJSON(0xc4200b0000, 0x934260, 0xc420952000, 0xc420033f90, 0xc420033f88)
	/home/foobar/.gopath/src/github.com/gorilla/websocket/json.go:22 +0x49
github.com/tomatorpg/tomatorpg/protocol/pubsub.messageTo(0xde6040, 0xc4202059d0, 0xde5f40, 0xc4200b0000, 0x934260, 0xc420952000, 0x6, 0xc420033fa0)
	/home/foobar/.gopath/src/github.com/tomatorpg/tomatorpg/protocol/pubsub/chan.go:134 +0x49
github.com/tomatorpg/tomatorpg/protocol/pubsub.(*WebsocketChan).run(0xc4202059d0)
	/home/foobar/.gopath/src/github.com/tomatorpg/tomatorpg/protocol/pubsub/chan.go:115 +0x76
created by github.com/tomatorpg/tomatorpg/protocol/pubsub.NewWebsocketChan
	/home/foobar/.gopath/src/github.com/tomatorpg/tomatorpg/protocol/pubsub/chan.go:73 +0xdb
```

**Comment by zzm88** [comment]
Same error here
